# Generated by Django 3.2.9 on 2022-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
